name: Push to prod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Git
      run: |
           git remote set-url origin https://GhostVaibhav:${{ secrets.PASS }}@github.com/GhostVaibhav/prod-Simple.git
           git config --global user.email "48472541+GhostVaibhav@users.noreply.github.com"
           git config --global user.name "Vaibhav Sharma"
           git fetch --prune origin
