name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: |
           git remote set-url origin https://GhostVaibhav:${{ secrets.PASS }}@github.com/GhostVaibhav/Simple.git
           git config user.email "48472541+GhostVaibhav@users.noreply.github.com"
           git config user.name "Vaibhav Sharma"
           npm install gh-pages --save-dev
           npm run deploy
           cd build
           echo "new.ghostvaibhav.me" > CNAME
           git init
           git add --all
           git commit -m "Added CNAME"
           git push -u origin gh-pages
