name: Uploading the published test site
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing prerequisites
        run: npm install
      - name: Building the site
        run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: site
          path: build
